 
name: DevOps Java CI Automation Pipeline 

on: 

push: 

branches: [ "main" ] 

pull_request: 

branches: [ "main" ] 

jobs: 

build-and-validate: 

runs-on: ubuntu-latest 

 

strategy: 

matrix: 

java-version: [17, 21] 

 

steps: 

-name: Checkout Source Code 

uses: actions/checkout@v4 

-name: Setup JDK ${{matrix.java-version}} 

uses: actions/setup-java@v4 

with: 

java-version:${{matrix.java-version}} 

distribution:'temurin' 

cache:'maven' 

-name: Run Automated Test Suites 

run:mvn test 
